import asyncio
import edge_tts
import random

async def main():
    text = """
Sach bataun...

Agar aapki NGO ki website nahi hai...
toh aap 50 percent donors tak pahunch hi nahi rahe ho.

Aaj ke time par log trust kaise karte hain...

Google karte hain...
Website check karte hain...
Phir decide karte hain donate karna hai ya nahi...

Agar aapki NGO online nahi hai...
toh log aapko serious hi nahi lete...

Isliye hum laaye hain...
Professional NGO Website...
sirf 7999 me...

Modern design...
Mobile friendly...
Donation ready...
Trust building layout...

Visit josmithservices.in...
ya DM now...

Aur jo website aap screen par dekh rahe ho...
uska link pinned comment me hai...
"""
    
    file_name = f"voice_{random.randint(1000,9999)}.mp3"

    communicate = edge_tts.Communicate(
        text=text,
        voice="en-IN-PrabhatNeural",
        rate="+12%",
        pitch="-4Hz"
    )

    await communicate.save(file_name)

    print(f"Voice saved as: {file_name}")

asyncio.run(main())
